Image based on BRT, documentation update and test suite
container-images/bind pull request #2
Opened 2017-06-22 10:22 UTC by rpitonak

2017-06-28 07:28 UTC, TomasTomecek requested changes
lovely work, just one nit and one question

2017-06-28 07:28 UTC, TomasTomecek commented on README.md
> +Bind Docker image
can we `s/Docker/container/`?

2017-06-28 07:28 UTC, TomasTomecek commented on tests/authoritative/sanity.py
> +        self.run("ls / | grep bin")
why do we have this test?

2017-06-28 07:28 UTC, TomasTomecek commented on tests/caching/requests.py
> +        self.run("dig @127.0.0.1 google.com | grep \"Query time: 0 msec\"")
awesome, I love this! checking whether it's caching the actual value

2017-07-10 08:18 UTC, rpitonak commented
Thank you for the review. Should be fixed now.

2017-07-10 13:03 UTC, TomasTomecek commented
LGTM; shall I merge, anyone else wanna take a look?

2017-07-11 13:31 UTC, TomasTomecek approved these changes

2017-07-11 13:31 UTC, merged